
[package]
main = "src/main.sn"
name = "snowball compiler"
version = "0.0.1"

[tests]
entry = "tests/main.sn"

[documentation]
entry = "./stdlib"
base = "/snowball/"

[benchmark]
entry = "./tests/main.sn"

[dependencies]
"rgb" = { version = "0.0.1" }
"is_even" = { version = "0.0.1" }