
#include "../../ir/values/Argument.h"
#include "../../ir/values/VariableDeclaration.h"
#include "../../utils/utils.h"
#include "LLVMBuilder.h"

#include <llvm/IR/Type.h>
#include <llvm/IR/Value.h>

namespace snowball {
namespace codegen {

void LLVMBuilder::visit(ir::VariableDeclaration* variable) {
    llvm::Value* store = nullptr;
    if (auto a = utils::cast<ir::Argument>(variable->getValue().get())) {
        auto id = a->getId();
        store = ctx->getSymbol(id);
    } else {
        auto id = variable->getId();
        store = ctx->getSymbol(id);
    }
    auto generatedValue = build(variable->getValue().get());
    auto isPointer = !!utils::dyn_cast<types::ReferenceType>(variable->getType());
    if (generatedValue->getType()->isPointerTy() && !isPointer && generatedValue->getType()->isFunctionTy())
        generatedValue = builder->CreateLoad(generatedValue->getType(), generatedValue);

    auto storeBaseType = getLLVMType(variable->getType());
    // case: calling autogenerated parent constructor
    if (storeBaseType != generatedValue->getType()) {
        generatedValue = builder->CreatePointerCast(generatedValue, storeBaseType);
    }

    builder->CreateStore(generatedValue, store);
}

} // namespace codegen
} // namespace snowball
